  CREATE TABLE PLAYBOOK 
   (	PLAYBOOK_ID NUMBER(10,0) NOT NULL ENABLE, 
	NAME VARCHAR2(255 CHAR), 
	TYPE VARCHAR2(255 CHAR), 
	 CONSTRAINT PLAYBOOK_PK PRIMARY KEY (PLAYBOOK_ID)
   )
  TABLESPACE LOCALTABLESPACE ;
  
  
    CREATE TABLE RULESET 
   (	RULESET_NAME VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	RULSET_ID NUMBER(10,0), 
	PLAYBOOK_TASK_TASK_ID NUMBER(10,0), 
	 CONSTRAINT RULESET_ENVIRONMENT_PK PRIMARY KEY (RULESET_NAME)
 ) 
  TABLESPACE LOCALTABLESPACE ;
  
  
  
  CREATE TABLE PLAYBOOK_TASK 
   (	TASK_ID NUMBER NOT NULL ENABLE, 
	PLAYBOOK_ID NUMBER, 
	TASK VARCHAR2(50 BYTE), 
	TASK_TYPE VARCHAR2(50 BYTE), 
	IS_REPEATABLE VARCHAR2(5 BYTE), 
	START_DATE DATE, 
	MODIFIED_ON DATE, 
	RULESET_NAME VARCHAR2(20 BYTE), 
	ID NUMBER(10,0), 
	RULESET_RULESET_NAME VARCHAR2(255 CHAR), 
	 CONSTRAINT PLAYBOOK_TASK_PK PRIMARY KEY (TASK_ID), 
	 CONSTRAINT PLAYBOOK_TASK_FK FOREIGN KEY (PLAYBOOK_ID)
	  REFERENCES PLAYBOOK (PLAYBOOK_ID) ON DELETE CASCADE ENABLE, 
	 CONSTRAINT TASK_RULESET_FK FOREIGN KEY (RULESET_NAME)
	  REFERENCES RULESET (RULESET_NAME) ON DELETE CASCADE ENABLE
   ) 
  TABLESPACE LOCALTABLESPACE ;
  
  
  
  
Insert into PLAYBOOK (PLAYBOOK_ID,NAME,TYPE) values (1,'Playbook_name_1','PlaybookType1');
Insert into PLAYBOOK (PLAYBOOK_ID,NAME,TYPE) values (2,'Playbook_name_2','PlaybookType2');


Insert into RULESET (RULESET_NAME,RULSET_ID) values ('Ruleset1',1);
Insert into RULESET (RULESET_NAME,RULSET_ID) values ('Ruleset2',2);


Insert into PLAYBOOK_TASK (TASK_ID,PLAYBOOK_ID,ID,TASK,TASK_TYPE,IS_REPEATABLE,START_DATE,MODIFIED_ON,RULESET_NAME,RULESET_RULESET_NAME) values (1,1,11,'Task1','tasktype1','true',to_date('07-FEB-20','DD-MON-RR'),to_date('12-FEB-20','DD-MON-RR'),'Ruleset1',null);
Insert into PLAYBOOK_TASK (TASK_ID,PLAYBOOK_ID,ID,TASK,TASK_TYPE,IS_REPEATABLE,START_DATE,MODIFIED_ON,RULESET_NAME,RULESET_RULESET_NAME) values (2,1,22,'Task1','tasktype2','true',to_date('07-FEB-20','DD-MON-RR'),null,'Ruleset1',null);

 